from fractions import Fraction

STATUS = {
  'SUCCESS': 'success',
  'ERROR': 'error',
}
CODE = {
  'DATA_SAVED': 'DATA_SAVED',
  'DATA_LOADED': 'DATA_LOADED',
  'DATA_FETCHED': 'DATA_FETCHED',
  'DATA_NOT_FOUND': 'DATA_NOT_FOUND',
  'FILE_NOT_FOUND': 'FILE_NOT_FOUND',
  'INVALID_JSON': 'INVALID_JSON',
  'UNKNOWN_KEY': 'UNKNOWN_KEY',

  'MISSING_REQUIRED_DATA': 'MISSING_REQUIRED_DATA',
  'DUPLICATE_DATA': 'DUPLICATE_DATA',
  'DUPLICATE_NAME': 'DUPLICATE_NAME',
  'INVALID_UID': 'INVALID_UID',
  'INVALID_USERNAME': 'INVALID_USERNAME',
  'INVALID_PASSWORD': 'INVALID_PASSWORD',
  'INVALID_EMAIL': 'INVALID_EMAIL',
  'DATA_VALID': 'DATA_VALID',

  'FAILED_LOGIN': 'FAILED_LOGIN',
  'INVALID_ACTION': 'INVALID_ACTION',
  'INVALID_PLAN': 'INVALID_PLAN',
  'INSUFFICIENT_MONEY': 'INSUFFICIENT_MONEY',
  'GAME_FINISHED': 'GAME_FINISHED',
  'SAVE_FAILED': 'SAVE_FAILED',
  'SLOT_FULL': 'SLOT_FULL',
}

STAT_MIN = 0
STAT_MAX = 100
TOTAL_MONTHS = 12
MONTHLY_ACTIONS = 3
DAYS_PER_ACTION = 10
DAY_PAUSE_SECONDS = 0.5
DAY_PAUSE_SPECIAL_SECONDS = 0.7

DEFAULT_STATS = {
  'money': 1_500_000,
  'intelligence': 5,
  'charm': 5,
  'stamina': 5,
  'stress': 0,
}

STAT_LABELS = {
  'money': '소지금',
  'intelligence': '지능',
  'charm': '매력',
  'stamina': '체력',
  'stress': '스트레스',
}
SCHEDULE_KIND_ACTION = 'action'
SCHEDULE_KIND_FIXED_EVENT = 'fixed_event'

OUTCOME_CRITICAL_SUCCESS = 'critical_success'
OUTCOME_SUCCESS = 'success'
OUTCOME_FAILURE = 'failure'
OUTCOME_CRITICAL_FAILURE = 'critical_failure'

OUTCOME_LABELS = {
  OUTCOME_CRITICAL_SUCCESS: '대성공',
  OUTCOME_SUCCESS: '성공',
  OUTCOME_FAILURE: '실패',
  OUTCOME_CRITICAL_FAILURE: '대실패',
}

OUTCOME_MULTIPLIERS = {
  OUTCOME_CRITICAL_SUCCESS: Fraction(2, 1),
  OUTCOME_SUCCESS: Fraction(1, 1),
  OUTCOME_FAILURE: Fraction(7, 10),
  OUTCOME_CRITICAL_FAILURE: Fraction(1, 2),
}

OUTCOME_CHANCES = (
  (OUTCOME_CRITICAL_SUCCESS, 10),
  (OUTCOME_SUCCESS, 60),
  (OUTCOME_FAILURE, 25),
  (OUTCOME_CRITICAL_FAILURE, 5),
)

CRITICAL_FAILURE_STRESS_BONUS = 2